import type {
  ScoreboardEntry,
  CTFDChallenge,
  CTFDSolve,
  CTFDSubmission,
} from '../types/ctfd';

export const demoScoreboard: ScoreboardEntry[] = [
  {
    pos: 1,
    account_id: 1,
    account_url: "/teams/1",
    account_type: "team",
    oauth_id: null,
    name: "Ennui185",
    score: 364,

  },
  {
    pos: 2,
    account_id: 6,
    account_url: "/teams/6",
    account_type: "team",
    oauth_id: null,
    name: "Art117",
    score: 169,

  },
  {
    pos: 3,
    account_id: 5,
    account_url: "/teams/5",
    account_type: "team",
    oauth_id: null,
    name: "Wes499",
    score: 147,

  },
  {
    pos: 4,
    account_id: 2,
    account_url: "/teams/2",
    account_type: "team",
    oauth_id: null,
    name: "Viral574",
    score: 146,

  },
  {
    pos: 5,
    account_id: 3,
    account_url: "/teams/3",
    account_type: "team",
    oauth_id: null,
    name: "Yolo268",
    score: 145,

  },
  {
    pos: 6,
    account_id: 7,
    account_url: "/teams/7",
    account_type: "team",
    oauth_id: null,
    name: "Echo194",
    score: 68,

  },
  {
    pos: 7,
    account_id: 4,
    account_url: "/teams/4",
    account_type: "team",
    oauth_id: null,
    name: "Cliche685",
    score: 39,

  },
  {
    pos: 8,
    account_id: 8,
    account_url: "/teams/8",
    account_type: "team",
    oauth_id: null,
    name: "Church-key762",
    score: 21,

  },
];

export const demoChallenges: CTFDChallenge[] = [
  {
    id: 3,
    name: "Trivia",
    category: "Multiple Choice",
    value: 42,
    description: "Test your knowledge with multiple choice questions.",
    max_attempts: null,
    state: "visible",
    type: "multiple_choice",
    solves: 5,
    solved_by_me: true,
  },
  {
    id: 5,
    name: "The Lost Park",
    category: "Forensics",
    value: 50,
    description: "A challenging forensics challenge about a lost national park.",
    max_attempts: null,
    state: "visible",
    type: "standard",
    solves: 4,
    solved_by_me: true,
  },
  {
    id: 1,
    name: "Squares",
    category: "Programming",
    value: 100,
    description: "A programming challenge involving squares and mathematics.",
    max_attempts: null,
    state: "visible",
    type: "code",
    solves: 3,
    solved_by_me: false,
  },
  {
    id: 2,
    name: "Too Many Puppers",
    category: "Forensics",
    value: 100,
    description: "Forensic analysis of puppy-related files.",
    max_attempts: null,
    state: "visible",
    type: "standard",
    solves: 3,
    solved_by_me: false,
  },
  {
    id: 4,
    name: "Reverse a String",
    category: "Programming",
    value: 100,
    description: "A simple string manipulation challenge.",
    max_attempts: null,
    state: "visible",
    type: "code",
    solves: 1,
    solved_by_me: false,
  },
];

export const demoSolves: CTFDSolve[] = [
  {
    id: 1,
    challenge_id: 3,
    challenge: {
      id: 3,
      name: "Trivia",
      category: "Multiple Choice",
      value: 42,
    },
    user_id: 25,
    user: {
      id: 25,
      name: "Bobby",
    },
    team_id: 4,
    date: "2025-11-05T03:30:00Z",
    type: "correct",
  },
  {
    id: 2,
    challenge_id: 5,
    challenge: {
      id: 5,
      name: "The Lost Park",
      category: "Forensics",
      value: 50,
    },
    user_id: 1,
    user: {
      id: 1,
      name: "Admin",
    },
    team_id: 1,
    date: "2025-11-05T03:20:00Z",
    type: "correct",
  },
  {
    id: 3,
    challenge_id: 1,
    challenge: {
      id: 1,
      name: "Squares",
      category: "Programming",
      value: 100,
    },
    user_id: 2,
    user: {
      id: 2,
      name: "Mary",
    },
    team_id: 8,
    date: "2025-11-05T03:10:00Z",
    type: "correct",
  },
];

export const demoSubmissions: CTFDSubmission[] = [
  {
    id: 1,
    challenge_id: 3,
    challenge: "Trivia",
    user_id: 25,
    user: "Bobby",
    team_id: 4,
    date: "2025-11-05T03:30:00Z",
    type: "correct",
    provided: "answer_1",
  },
  {
    id: 2,
    challenge_id: 5,
    challenge: "The Lost Park",
    user_id: 1,
    user: "Admin",
    team_id: 1,
    date: "2025-11-05T03:20:00Z",
    type: "correct",
    provided: "flag{real_flag}",
  },
  {
    id: 3,
    challenge_id: 1,
    challenge: "Squares",
    user_id: 2,
    user: "Mary",
    team_id: 8,
    date: "2025-11-05T03:10:00Z",
    type: "correct",
    provided: "42",
  },
];
